language: cpp
compiler:
  - gcc
  - clang
env:
  - WINDOWS=32
  - WINDOWS=64
  - WINDOWS=no
before_install: ./util/travis/before_install.sh
script: ./util/travis/script.sh
notifications:
  email: false
matrix:
  fast_finish: true
  exclude:
    - env: WINDOWS=32
      compiler: clang
    - env: WINDOWS=64
      compiler: clang
